version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    networks:
      - front
      - backend
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    restart: always

  wordpress:
    image: wordpress:fpm
    networks:
      - backend
      - databases
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    restart: always

networks:
  front:
    external:
      name: front
  databases:
    external:
      name: databases
  backend:
