version: '3'
services:
  wordpress:
    image: wordpress
    networks:
      - front
      - databases
    volumes:
      - ./wordpress:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    restart: always

networks:
  front:
    external:
      name: front
  databases:
    external:
      name: databases
